name: Rust + Svelte/Tauri Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  NODE_VERSION: 20

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Checkout repo
      - uses: actions/checkout@v4

      - name: ls
        run: |
          ls
          cd ReLaunchpad
          
      # Set up Node
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      # Install frontend dependencies
      - name: Install frontend dependencies
        run: |
          ls
          npm install
        working-directory: ReLaunchpad/Relaunchpad

      # Build frontend
      - name: Build frontend
        run: npm run build
        working-directory: ReLaunchpad/Relaunchpad

      # Set up Rust
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # Build Rust library
      - name: Build Rust library
        run: cargo build --verbose
        working-directory: ReLaunchpad/Relaunchpad

      # Run Rust tests
      - name: Run Rust tests
        run: cargo test --verbose
        working-directory: ReLaunchpad/Relaunchpad
