name: Rust + Svelte/Tauri Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  NODE_VERSION: 20

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Checkout repo
      - uses: actions/checkout@v4

      # Set up Node
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: 'ReLaunchpad/package-lock.json'

      # Install frontend dependencies
      - name: Install frontend dependencies
        run: npm install
        working-directory: ReLaunchpad

      # Cache Rust/Cargo dependencies
      - name: Cache Cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: cargo-cache-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-cache-${{ runner.os }}-

      # Build Tauri app (frontend + Rust backend) in release mode
      - name: Build Tauri app
        run: npm run tauri:build
        working-directory: ReLaunchpad

      # Run Rust tests (release)
      - name: Run Rust tests
        run: cargo test --release
        working-directory: ReLaunchpad/src-tauri

      # Upload built app as artifact
      - name: Upload Tauri App Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ReLaunchpad-macos
          path: ReLaunchpad/src-tauri/target/release/bundle/macos
